name: Figma Variables Sync
on: workflow_dispatch
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Fetch Figma API Data 📦
        uses: JamesIves/fetch-api-data-action@releases/v2
        with:
          endpoint: https://api.figma.com/v1/files/MoOEVw9unAKquzEvS3xmRC/variables/local
          configuration: '{ "method": "GET", "headers": {"X-FIGMA-TOKEN": "figd_awj-_-C2suKicYdGLTdj_zcQtDykqa35yqp5pEy7"} }'
          save-name: figma

      - name: Commit changes
        run: |
          git config user.name crunchbase-ci
          git config user.email team_infrastructure_service_account@crunchbase.com
          git checkout -b crunchbase-ci/update-figma-variables
          git add .
          git commit -m "CB-00000 Update Figma Variables"
          git push origin crunchbase-ci/update-figma-variables --force

      # - name: Create pull request
      #   uses: actions/github-script@v6.4.1
      #   with:
      #     github-token: ${{ secrets.CI_GITHUB_TOKEN }}
      #     script: |
      #       const script = require('./.github/scripts/create-yarn-lock-pull.js');
      #       await script(github, context, core);
      - name: Create Pull Request
        run: gh pr create -B main -H crunchbase-ci/update-figma-variables --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
