name: Figma Variables Sync
on: workflow_dispatch
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4.0.0

      - name: Install dependencies
        run: npm install

      - name: Fetch Figma API Data 📦
        uses: JamesIves/fetch-api-data-action@releases/v2
        with:
          endpoint: https://api.figma.com/v1/files/MoOEVw9unAKquzEvS3xmRC/variables/local
          configuration: '{ "method": "GET", "headers": {"X-FIGMA-TOKEN": "figd_OMgaTAlW9EVeYnbxgKJfayy_XbN9WPCX4aA57AkV"} }'
          save-name: figma

      - name: Print Figma Data 📦
        run: npm run print-test

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: update-figma-variables
      - name: Create Pull Request
        run: gh pr create -B main -H update-figma-variables --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
