name: Figma Variables Sync
on: workflow_dispatch
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4.0.0

      - name: Fetch Figma API Data 📦
        uses: JamesIves/fetch-api-data-action@releases/v2
        with:
          endpoint: https://api.figma.com/v1/files/MoOEVw9unAKquzEvS3xmRC/variables/local
          configuration: '{ "method": "GET", "headers": {"X-FIGMA-TOKEN": "figd_d5rKAibR_YCdBF8243B7nIhCB80s8LdQFLhRiezX"} }'
          save-name: figma

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: update-figma-variables

      # - name: Create pull request
      #   uses: actions/github-script@v6.4.1
      #   with:
      #     github-token: ${{ secrets.CI_GITHUB_TOKEN }}
      #     script: |
      #       const script = require('./.github/scripts/create-yarn-lock-pull.js');
      #       await script(github, context, core);
      - name: Create Pull Request
        run: gh pr create -B main -H update-figma-variables --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
